image: docker:18.09

services:
  - docker:18.09-dind

variables:
  DOCKER_HOST: tcp://localhost:2375

stages:
  - build

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build dev:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    # - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:dev_$V
    - docker push $CI_REGISTRY_IMAGE 
  tags:
    - kubernetes
  only:
    - master


# build master:
#   stage: build
#   script:
#     - docker pull $CI_REGISTRY_IMAGE:beta
#     - docker tag $CI_REGISTRY_IMAGE:beta $CI_REGISTRY_IMAGE
#     - docker push $CI_REGISTRY_IMAGE
#   tags:
#     - kubernetes
#   only:
#     - master

# build tag:
#   stage: build
#   script:
#     - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
#     - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   tags:
#     - kubernetes
#   only:
#     - tags
